baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Tataee"
theme = "PaperMod"

[taxonomies]
  tag = "tags"
  category = "categories"

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
[params.assets]
  customCSS = ["css/extended/custom.css"]

  mainSections = ["posts"]

  [[params.socialIcons]]
    name = "instagram"
    url = "https://instagram.com/365ailier"

  [[params.socialIcons]]
    name = "mastodon"
    url = "https://alive.bar/@Tatachibubao"

  [params.profileMode]
    enabled = true
    title = "Tataee"
    subtitle = "纯碎碎念 | 今天动了吗？ | Research"
    imageUrl = "/images/avatar.jpg"
    imageWidth = 150
    imageHeight = 150
    imageTitle = "avatar"

[[menu.main]]
  name = "Blog"
  url = "/posts/"
  weight = 1

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 2

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 3
